name: Auto Update

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: 
    -cron: '* * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y libusb-1.0-0-dev libudev-dev
    - name: Build
      run: cargo update
